name: OctoBot-Project-Website

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install and build site 🔧
        run: |
          yarn install
          gem install bundler
          bundle install
          jekyll build

      - name: Deploy 🚀
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./_site
          CLEAN: true # Automatically remove deleted files from the deploy branch

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ failure() }}

    steps:
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          status: Failure
          webhook: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
